command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "$DATABRICKS_APP_PORT"
  - --server.address
  - "0.0.0.0"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "11aa985a3f1d046f"
  - name: GATEWAY-ACCESS_TOKEN
    value: "dapib1dae45983597cc236bdf1a6389d37aa"
